services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: xoface-api
    ports:
      - "8000:8000"
    volumes:
      - xoface-models:/app/models
      - xoface-dvc-config:/app/.dvc
    environment:
      - PYTHONPATH=/app
      - DEVICE=cpu
      - DVC_USER=pawarit.jamjod
      - DVC_PASSWORD=5718b4a81a27588ff3ab03b1ed799041eff3eb21
    command: python api/api.py

  ui:
    build:
      context: .
      dockerfile: docker/Dockerfile.ui
    container_name: xoface-ui
    ports:
      - "8501:8501"
    environment:
      - PYTHONPATH=/app
      - FAST_API_URL=http://10.4.41.80:8000
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501

volumes:
  xoface-models:
  xoface-dvc-config:
