# Access Prometheus Server at http://localhost:9090/
# Access Grafana UI at http://localhost:3000/

global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['api:8000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']